### ISSUE TITLE
Rootstock fails to build with latest manubot PyPI version

### ISSUE THREAD

**Issue by michaelmhoffman** [manubot/rootstock#228]
I can't build a current copy of rootstock with the latest version of manubot on pip:

```
(manubot) mhoffman@mhoffman2 ~/src/collab/rootstock-clean
$ git rev-parse --verify HEAD
b9e1d42b51a1b6a2807ce82840c49f1791f65ac5

(manubot) mhoffman@mhoffman2 ~/src/collab/rootstock-clean
$ manubot --version
v0.2.3

(manubot) mhoffman@mhoffman2 ~/src/collab/rootstock-clean
$ sh build/build.sh 
Retrieving and processing reference metadata
## INFO
Manuscript content parts:
00.front-matter
01.abstract
02.delete-me
90.back-matter
## INFO
8 unique citations strings extracted from text
8 unique standard citations    
Traceback (most recent call last):
  File "/home/mhoffman/.conda/envs/manubot/bin/manubot", line 10, in <module>
    sys.exit(main())
  File "/home/mhoffman/.conda/envs/manubot/lib/python3.6/site-packages/manubot/command.py", line 141, in main
    function(args)
  File "/home/mhoffman/.conda/envs/manubot/lib/python3.6/site-packages/manubot/process/process_command.py", line 29, in cli_process
    prepare_manuscript(args)
  File "/home/mhoffman/.conda/envs/manubot/lib/python3.6/site-packages/manubot/process/util.py", line 331, in prepare_manuscript
    generate_csl_items(args, citation_df)
  File "/home/mhoffman/.conda/envs/manubot/lib/python3.6/site-packages/manubot/process/util.py", line 265, in generate_csl_items
    manual_refs = read_manual_references(args.manual_references_path)
  File "/home/mhoffman/.conda/envs/manubot/lib/python3.6/site-packages/manubot/process/util.py", line 44, in read_manual_references
    standard_citation = csl_item.pop('standard_citation')
KeyError: 'standard_citation'
```

Expected: not to get this error.

**Comment by dhimmel** [comment]
I think the cause of this error is that the version of rootstock you're using expects a specific version of the `manubot` python package, as is specified in `build/environment.yml`:

https://github.com/manubot/rootstock/blob/b9e1d42b51a1b6a2807ce82840c49f1791f65ac5/build/environment.yml#L22

If you install the environment as per [these instructions](https://github.com/manubot/rootstock/tree/b9e1d42b51a1b6a2807ce82840c49f1791f65ac5/build#environment), hopefully things will work.

Also we should create a PyPI release soon, but in general there is no gaurantee that the latest PyPI version is what's needed for the latest rootstock version. Will think of ways we can avoid this confusion or make this less likely to happen.

**Comment by michaelmhoffman** [comment]
Thanks, that works.
