### ISSUE TITLE
manubot called from script fails

### ISSUE THREAD

**Issue by PJSpoti** [manubot/rootstock#361]
Something must have changed between yesterday and today. Yesterday manubot worked smoothly as expected. Today it throws exceptions.
Here is an output:

```python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/manubot", line 11, in <module>
    load_entry_point('manubot==0.4.1', 'console_scripts', 'manubot')()
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/command.py", line 240, in main
    function = import_function(args.function)
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/util.py", line 23, in import_function
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/cite/__init__.py", line 5, in <module>
    from manubot.cite.citekey import citekey_to_csl_item
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/cite/citekey.py", line 8, in <module>
    import typing as tp
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
^CTraceback (most recent call last):
  File "scanner.py", line 16, in <module>
    for data in sys.stdin:
KeyboardInterrupt
```

I would be glad if somebody could help me sorting out this issue.
Thank you in advance and kind regards,
PJSpoti

**Comment by agitter** [comment]
The error `AttributeError: type object 'Callable' has no attribute '_abc_registry'` suggests to me that this is not a bug with the Manubot package but rather other parts of the Python environment.  Searching that error message turns up this issue that pertains to `pip` and the `typing` package: https://github.com/pypa/pip/issues/8272

Does that issue seem relevant to your error?  Do you have the `typing` package installed?

Manubot v0.4.1 was released on August 15.  However, if your scripts worked yesterday, that suggests that the v0.4.1 isn't the root cause.

**Comment by dhimmel** [comment]
The `KeyboardInterrupt` catches my attention:

> Raised when the user hits the interrupt key (normally Control-C or Delete). During execution, a check for interrupts is made regularly.

@PJSpoti did you interrupt the process? Was that because it was hung indefinitely? Perhaps hung waiting for stdin?

What command were you running?

**Comment by PJSpoti** [comment]
@dhimmel @agitter 
Thank you very much. I indeed killed the process in the end since it was running indefinitely.
This is the portion I get when I just enter the ISBN and press Enter:
Traceback (most recent call last):
  File "/usr/local/bin/manubot", line 11, in <module>
    load_entry_point('manubot==0.4.1', 'console_scripts', 'manubot')()
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/command.py", line 240, in main
    function = import_function(args.function)
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/util.py", line 23, in import_function
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/cite/__init__.py", line 5, in <module>
    from manubot.cite.citekey import citekey_to_csl_item
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/cite/citekey.py", line 8, in <module>
    import typing as tp
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

@agitter Thank you very much I will look into it. Although, I only rebooted the computer, that is basically all that has changed. Thank you for pointing me to a possible solution.

**Comment by PJSpoti** [comment]
@agitter Yes, typing is installed indeed.

**Comment by dhimmel** [comment]
@PJSpoti is this from running `manubot cite` or something else?

If you could provide the exact command that is failing, that would be very helpful

**Comment by PJSpoti** [comment]
@dhimmel: Basically it is just manubot cite isbn:XXXXXXXXXXXXX. I also want to thank you for your program and your effort! It was running smoothly yesterday and was simply amazing.

**Comment by dhimmel** [comment]
Can you try the following two commands, and report whether they work. And if not, provide the error message:

1. `manubot cite isbn:1250170249`

2. `manubot cite --render isbn:1250170249`

**Comment by PJSpoti** [comment]
This is the first output: 
manubot cite isbn:1250170249
Traceback (most recent call last):
  File "/usr/local/bin/manubot", line 11, in <module>
    load_entry_point('manubot==0.4.1', 'console_scripts', 'manubot')()
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/command.py", line 240, in main
    function = import_function(args.function)
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/util.py", line 23, in import_function
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/cite/__init__.py", line 5, in <module>
    from manubot.cite.citekey import citekey_to_csl_item
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/cite/citekey.py", line 8, in <module>
    import typing as tp
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'


manubot cite --render isbn:1250170249
Traceback (most recent call last):
  File "/usr/local/bin/manubot", line 11, in <module>
    load_entry_point('manubot==0.4.1', 'console_scripts', 'manubot')()
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/command.py", line 240, in main
    function = import_function(args.function)
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/util.py", line 23, in import_function
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/cite/__init__.py", line 5, in <module>
    from manubot.cite.citekey import citekey_to_csl_item
  File "/usr/local/lib/python3.7/dist-packages/manubot-0.4.1-py3.7.egg/manubot/cite/citekey.py", line 8, in <module>
    import typing as tp
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/lib/python3.7/dist-packages/typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'


Sorry.

**Comment by agitter** [comment]
@PJSpoti I have not thought carefully about this, but related comments (https://github.com/ethereum/eth-abi/issues/131#issuecomment-633512026) indicate that the separate `typing` package is not needed for Python 3.7.  Some users were able to fix this error by uninstalling the package using `pip uninstall typing`.  However, I cannot predict how that might affect other Python packages you use.  Before uninstalling `typing`, you could make a note of the version you current have installed so you could reinstall that version via pip later if it is needed.

**Comment by PJSpoti** [comment]
@agitter 
Thank you for your help. I tried uninstalling typing and reinstalling - unfortunately - to no betterment. I ended up reinstalling all of python my system and now it works again like a charm. 
I use Debian 10 with the libraries in their provided versions.

**Comment by PJSpoti** [comment]
Thank you for your time and effort and especially thank you for providing the community with manubot (it really makes life a lot easier when it comes to garnering information about books (for articles and so forth).

**Comment by agitter** [comment]
I'm glad it's working again even though none of our specific suggestions helped.  And thanks for the positive feedback on Manubot!
