### ISSUE TITLE
Upgrade manubot to fix pubmed API calls.

### ISSUE THREAD

**Issue by tiwns** [manubot/rootstock#485]
Hello,

I have been successful in using Manubot for previous repositories. However, when setting up a new repository using ```bash <( curl --location https://github.com/manubot/rootstock/raw/main/setup.bash )```, I receive this error in Github Actions: Upgrade Manubot to fix pubmed API calls. 

Also, I do not need pubmed for this work.

Thank you.

**Comment by dhimmel** [comment]
Hmm "Upgrade Manubot to fix pubmed API calls." is the commit message for b7a5c3f80d23ecb53de321822e2a2239209e01c7, but isn't an actual error that Manubot issues.

**Comment by tiwns** [comment]
Yes, its Commit [b7a5c3f]. It is failing for my newer repositories but worked fine on the old repositories.

**Comment by dhimmel** [comment]
Can you copy the GitHub Actions log and and paste it here? Will be helpful to see more about the error and the messages proceeding it.

**Comment by tiwns** [comment]
Here it is:

`Run bash ci/deploy.sh
Already on 'main'
M	webpage/README.md
Your branch is up to date with 'origin/main'.
[INFO] Detected MANUBOT_ACCESS_TOKEN. Will deploy via HTTPS.
fatal: couldn't find remote ref gh-pages
[INFO] could not fetch gh-pages or output from origin.
## WARNING
Checkout returned a nonzero exit status. See output:
fatal: invalid reference: gh-pages
remote: Write access to repository not granted.
fatal: unable to access '[removed address]': The requested URL returned error: 403
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/manubot/bin/ghp-import", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/share/miniconda3/envs/manubot/lib/python3.11/site-packages/ghp_import.py", line 300, in main
    ghp_import(args.pop("directory"), **args)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.11/site-packages/ghp_import.py", line 285, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'])
  File "/usr/share/miniconda3/envs/manubot/lib/python3.11/site-packages/ghp_import.py", line 119, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'output']' returned non-zero exit status 128.
Error: Process completed with exit code 1.`

**Comment by tiwns** [comment]
In addition for an organization repository, I receive this error:


Error: .github#L1
conda-incubator/setup-miniconda@v2 is not allowed to be used in XXXX. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following:

**Comment by dhimmel** [comment]
Regarding "Write access to repository not granted", if you go to `/settings/actions` can you see which box is checked:

> ![image](https://user-images.githubusercontent.com/1117703/218799710-500d3c90-e04a-471f-ad25-f76ce45ec57d.png)

If you add the following to `.github/workflows/manubot.yaml`, that should also fix it ([docs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)):

```yaml
permissions:
  contents: write
```

We should probably add this to rootstock, but would be good if you can confirm it fixes the problem.

> Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following

Looks like the organization has a setting that blocks the `conda-incubator/setup-miniconda` action. See if someone with admin access to the organization can allow this and the other dependent actions.
