### ISSUE TITLE
Run failed:  pages build and deployment 

### ISSUE THREAD

**Issue by aemcdani** [manubot/rootstock#505]
I created a repository to use manubot in ([https://github.com/UCSC-Treehouse/TUBI-2023](https://github.com/UCSC-Treehouse/TUBI-2023)). I'd like CI to run on github. I ran 
`bash <( curl --location https://github.com/manubot/rootstock/raw/main/setup.bash)` locally. When I update the code in the repository (e.g. content/01.abstract.md), I get an error message: Run failed: pages build and deployment - main (3310304).

<img width="716" alt="image" src="https://github.com/manubot/rootstock/assets/138170457/54036a2a-5a39-4358-bc75-47a7001cf9cd">

`Run actions/jekyll-build-pages@v1
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv108_d30a3e --label 5bedb4 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/TUBI-2023/TUBI-2023":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.8
Configuration file: none
  Logging at level: debug
      GitHub Pages: github-pages v228
      GitHub Pages: jekyll v3.9.3
             Theme: jekyll-theme-primer
      Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0
         Requiring: jekyll-github-metadata
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/usr/local/bundle/gems/pathutil-0.16.2/lib/pathutil.rb:292:in `in_path?': No such file or directory @ rb_check_realpath_internal - /github/workspace/webpage/images (Errno::ENOENT)
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/entry_filter.rb:83:in `symlink_outside_site_source?'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/entry_filter.rb:74:in `symlink?'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/entry_filter.rb:35:in `block in filter'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/entry_filter.rb:33:in `reject'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/entry_filter.rb:33:in `filter'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:117:in `filter_entries'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:42:in `block in read_directories'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:42:in `chdir'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:42:in `read_directories'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:80:in `block in retrieve_dirs'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:76:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:76:in `retrieve_dirs'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:51:in `read_directories'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:16:in `read'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:164:in `read'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:69:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
         Requiring: jekyll-seo-tag
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
   GitHub Metadata: Initializing...
            Source: /github/workspace/.
       Destination: /github/workspace/./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
github-pages 228 | Error:  No such file or directory @ rb_check_realpath_internal - /github/workspace/webpage/images`

**Comment by agitter** [comment]
I wasn't able to diagnose the details of that error message, but I believe I understand the problem by looking at the https://github.com/UCSC-Treehouse/TUBI-2023 repository. That repository has some of the Manubot rootstock files but not all of them. Specifically, I noticed it doesn't have the files that run the GitHub Actions workflow that run Manubot on the content and update the files on the `output` and `gh-pages` branches. That left the repository in an incomplete state where GitHub Pages is trying to deploy something but failing.

Did you make a few initial commits in that repository before running the Manubot setup script? The setup script will only work on a newly initialized empty repository. It needs to be able to copy the full rootstock commit history to the new repository (relevant to the recent discussion here #504).

If you did not customize too many files in your repository, the most reliable solution may be to create a new empty repository and run the setup script again before commiting anything to that repository. If that succeeds, you could copy any customized files from https://github.com/UCSC-Treehouse/TUBI-2023 into the new repository.
